service: my-app
plugins:
  - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

# ロールの付与
role: ''

# VPCの設定
vpc:
  securityGroupIds:
    - sg-xxxxxxxxxxxxxxxxx
  subnetIds:
    - subnet-xxxxxxxxxxxxxxxxx
    - subnet-xxxxxxxxxxxxxxxxx
    - subnet-xxxxxxxxxxxxxxxxx

# 関数
functions:
  condition:
    handler: condition.condition
    events:
      - http:
          path: condition
          method: get
  save:
    handler: condition.save
    events:
      - http:
          path: condition/save
          method: post
  get_csv:
    handler: condition.get_csv
    events:
      - http:
          path: condition/csv
          method: get
  graph:
    handler: condition.graph
    events:
      - http:
          path: graph
          method: get
  graph_day:
    handler: condition.graph_day
    events:
      - http:
          path: graph_day
          method: get
  graph_month:
    handler: condition.graph_month
    events:
      - http:
          path: graph_month
          method: get
  set_licesence:
    handler: license.set
    events:
      - http:
          path: license
          method: post
  get_licesence:
    handler: license.get
    events:
      - http:
          path: license
          method: get
  delete_license:
    handler: license.delete
    events:
      - http:
          path: license
          method: delete
  get_user:
    handler: user.get
    events:
      - http:
          path: user
          method: get
  update_user_confirm:
    handler: user.update_confirm
    events:
      - http:
          path: user/confirm
          method: post
  regist_user:
    handler: user.regist_user
    events:
      - http:
          path: user/regist
          method: post
  get_staff:
    handler: staff.get
    events:
      - http:
          path: staff
          method: get
  update_staff_confirm:
    handler: staff.update_confirm
    events:
      - http:
          path: staff/confirm
          method: post
  regist_staff:
    handler: staff.regist_user
    events:
      - http:
          path: staff/regist
          method: post
  get_log:
    handler: log.get
    events:
      - http:
          path: log
          method: get
  set_log:
    handler: log.set
    events:
      - http:
          path: log/regist
          method: post
